createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table dimdate
			lineageTag: 42d0f417-ffba-424d-907b-c2a73dde0a71
			dataCategory: Time

			column DateKey
				dataType: int64
				formatString: 0
				lineageTag: 00362b37-6a09-4310-b430-29359c75f0ef
				summarizeBy: none
				sourceColumn: DateKey

				annotation SummarizationSetBy = Automatic

			column FullDateAlternateKey
				dataType: dateTime
				isKey
				formatString: Long Date
				lineageTag: e9783189-47d8-4681-b752-1f900f62a078
				summarizeBy: none
				sourceColumn: FullDateAlternateKey

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column DayNumberOfWeek
				dataType: int64
				formatString: 0
				lineageTag: bef4c704-a42b-4d3d-add5-7c26eabd7045
				summarizeBy: none
				sourceColumn: DayNumberOfWeek

				annotation SummarizationSetBy = Automatic

			column EnglishDayNameOfWeek
				dataType: string
				lineageTag: 766adf3a-8a8b-4b34-a075-d3de65b61fbd
				summarizeBy: none
				sourceColumn: EnglishDayNameOfWeek

				annotation SummarizationSetBy = Automatic

			column SpanishDayNameOfWeek
				dataType: string
				lineageTag: 6e370e47-7fc0-487e-b22c-7ce9bb86c71a
				summarizeBy: none
				sourceColumn: SpanishDayNameOfWeek

				annotation SummarizationSetBy = Automatic

			column FrenchDayNameOfWeek
				dataType: string
				lineageTag: 0fc7515a-c339-4d05-85d4-7c0b463b747c
				summarizeBy: none
				sourceColumn: FrenchDayNameOfWeek

				annotation SummarizationSetBy = Automatic

			column DayNumberOfMonth
				dataType: int64
				formatString: 0
				lineageTag: 312bb094-fc24-44cd-ae2e-9e92b9dd4db6
				summarizeBy: none
				sourceColumn: DayNumberOfMonth

				annotation SummarizationSetBy = Automatic

			column DayNumberOfYear
				dataType: int64
				formatString: 0
				lineageTag: a3b761d9-5d3f-4a05-aa56-7de03c21ee15
				summarizeBy: none
				sourceColumn: DayNumberOfYear

				annotation SummarizationSetBy = Automatic

			column WeekNumberOfYear
				dataType: int64
				formatString: 0
				lineageTag: 8ea6314f-3cb4-4de2-bba2-081ae9293b68
				summarizeBy: none
				sourceColumn: WeekNumberOfYear

				annotation SummarizationSetBy = Automatic

			column EnglishMonthName
				dataType: string
				lineageTag: ffbdc41b-2858-488f-a003-3e14071df109
				summarizeBy: none
				sourceColumn: EnglishMonthName

				annotation SummarizationSetBy = Automatic

			column SpanishMonthName
				dataType: string
				lineageTag: 552aa63a-3ab9-4a83-982e-1cfade2e97f4
				summarizeBy: none
				sourceColumn: SpanishMonthName

				annotation SummarizationSetBy = Automatic

			column FrenchMonthName
				dataType: string
				lineageTag: ef4c5248-6df4-4a80-a847-4c34367f1d33
				summarizeBy: none
				sourceColumn: FrenchMonthName

				annotation SummarizationSetBy = Automatic

			column MonthNumberOfYear
				dataType: int64
				formatString: 0
				lineageTag: 9e925e4e-04c4-4810-b874-a8ef750ba11a
				summarizeBy: none
				sourceColumn: MonthNumberOfYear

				annotation SummarizationSetBy = Automatic

			column CalendarQuarter
				dataType: int64
				formatString: 0
				lineageTag: 7ec59eab-efbc-421e-9c25-54d22f37ec25
				summarizeBy: none
				sourceColumn: CalendarQuarter

				annotation SummarizationSetBy = Automatic

			column CalendarYear
				dataType: int64
				formatString: 0
				lineageTag: 7cc51914-468c-49f4-9f6e-1e3aed078b38
				summarizeBy: none
				sourceColumn: CalendarYear

				annotation SummarizationSetBy = Automatic

			column CalendarSemester
				dataType: int64
				formatString: 0
				lineageTag: 5e993c7b-271f-4c83-a4c5-390dd79fdc7c
				summarizeBy: none
				sourceColumn: CalendarSemester

				annotation SummarizationSetBy = Automatic

			column FiscalQuarter
				dataType: int64
				formatString: 0
				lineageTag: eaf95d07-d2e3-4a54-9e56-b52fb709573a
				summarizeBy: none
				sourceColumn: FiscalQuarter

				annotation SummarizationSetBy = Automatic

			column FiscalYear
				dataType: int64
				formatString: 0
				lineageTag: db2713a1-f91a-40b9-adb1-3a32564e8ca0
				summarizeBy: none
				sourceColumn: FiscalYear

				annotation SummarizationSetBy = Automatic

			column FiscalSemester
				dataType: int64
				formatString: 0
				lineageTag: 5ab386ba-c101-4cf5-ad08-0deaf1cd80ac
				summarizeBy: none
				sourceColumn: FiscalSemester

				annotation SummarizationSetBy = Automatic

			partition dimdate = m
				mode: import
				source =
						let
						    Source = Sql.Database("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com", "Lakehouse_Adventure_Works"),
						    dbo_dimdate = Source{[Schema="dbo",Item="dimdate"]}[Data]
						in
						    dbo_dimdate

			annotation PBI_ResultType = Table

		table dimproduct
			lineageTag: f9866f64-4b86-401c-b7dc-72bcbff97927

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: 61f37efe-6401-445f-918e-f04376f0ef51
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			column ProductAlternateKey
				dataType: string
				lineageTag: 72b0fe30-f87f-4652-b7d4-a899f57007c7
				summarizeBy: none
				sourceColumn: ProductAlternateKey

				annotation SummarizationSetBy = Automatic

			column ProductSubcategoryKey
				dataType: double
				lineageTag: cde823fa-d9b4-4d37-ab17-08ca910ae4b2
				summarizeBy: none
				sourceColumn: ProductSubcategoryKey

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column WeightUnitMeasureCode
				dataType: string
				lineageTag: 3a0ed983-8291-479d-85d6-735439797f3f
				summarizeBy: none
				sourceColumn: WeightUnitMeasureCode

				annotation SummarizationSetBy = Automatic

			column SizeUnitMeasureCode
				dataType: string
				lineageTag: b6596139-e01b-4fee-9108-c2f6db51e749
				summarizeBy: none
				sourceColumn: SizeUnitMeasureCode

				annotation SummarizationSetBy = Automatic

			column EnglishProductName
				dataType: string
				lineageTag: 54e63498-2650-4383-a5a0-cc5e53939b4f
				summarizeBy: none
				sourceColumn: EnglishProductName

				annotation SummarizationSetBy = Automatic

			column SpanishProductName
				dataType: string
				lineageTag: 44a91c52-1b76-4d94-b03c-7e117e263576
				summarizeBy: none
				sourceColumn: SpanishProductName

				annotation SummarizationSetBy = Automatic

			column FrenchProductName
				dataType: string
				lineageTag: 26609a9d-b716-4c89-9974-fcdc7c1476e5
				summarizeBy: none
				sourceColumn: FrenchProductName

				annotation SummarizationSetBy = Automatic

			column StandardCost
				dataType: double
				lineageTag: 71a1aabc-39ec-45e6-9afc-1da0082bca3d
				summarizeBy: none
				sourceColumn: StandardCost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column FinishedGoodsFlag
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				lineageTag: b5406585-5b3f-4ecc-8b4e-119106861432
				summarizeBy: none
				sourceColumn: FinishedGoodsFlag

				annotation SummarizationSetBy = Automatic

			column Color
				dataType: string
				lineageTag: 1f154c64-3d61-4a6f-8fdc-b4c0ebf3ed08
				summarizeBy: none
				sourceColumn: Color

				annotation SummarizationSetBy = Automatic

			column SafetyStockLevel
				dataType: int64
				formatString: 0
				lineageTag: 837c92ea-c6bb-4cf3-9147-0698fa4195af
				summarizeBy: none
				sourceColumn: SafetyStockLevel

				annotation SummarizationSetBy = Automatic

			column ReorderPoint
				dataType: int64
				formatString: 0
				lineageTag: 2b28af1b-b08c-49d1-a457-5dd4ffddc0bc
				summarizeBy: none
				sourceColumn: ReorderPoint

				annotation SummarizationSetBy = Automatic

			column ListPrice
				dataType: double
				lineageTag: 7f2d6112-48a3-4b61-89ce-b1551c25abd5
				summarizeBy: none
				sourceColumn: ListPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Size
				dataType: string
				lineageTag: 872583ac-25ef-4b5f-afce-301e3567190b
				summarizeBy: none
				sourceColumn: Size

				annotation SummarizationSetBy = Automatic

			column SizeRange
				dataType: string
				lineageTag: baef68da-23eb-4302-869e-4cdd319ae18d
				summarizeBy: none
				sourceColumn: SizeRange

				annotation SummarizationSetBy = Automatic

			column Weight
				dataType: double
				lineageTag: 169fbc29-0016-4a31-ac30-52aaaf65e98b
				summarizeBy: none
				sourceColumn: Weight

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column DaysToManufacture
				dataType: int64
				formatString: 0
				lineageTag: 008d3172-e05b-44ba-ac10-b2504e0e57a2
				summarizeBy: none
				sourceColumn: DaysToManufacture

				annotation SummarizationSetBy = Automatic

			column ProductLine
				dataType: string
				lineageTag: 0eb20ea9-d413-4edf-8348-2145cefb7a7c
				summarizeBy: none
				sourceColumn: ProductLine

				annotation SummarizationSetBy = Automatic

			column DealerPrice
				dataType: double
				lineageTag: e1809ef8-6e5e-4ba1-b398-f85c7c33b8b2
				summarizeBy: none
				sourceColumn: DealerPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Class
				dataType: string
				lineageTag: 6c482b60-85eb-4e38-83e0-17f210dd5f9e
				summarizeBy: none
				sourceColumn: Class

				annotation SummarizationSetBy = Automatic

			column Style
				dataType: string
				lineageTag: 5829ace8-c4d9-4bb6-aba5-bdf3ec13b8dd
				summarizeBy: none
				sourceColumn: Style

				annotation SummarizationSetBy = Automatic

			column ModelName
				dataType: string
				lineageTag: d6bd5e4d-a82c-4bd4-bf0a-0d5b78d4743e
				summarizeBy: none
				sourceColumn: ModelName

				annotation SummarizationSetBy = Automatic

			column EnglishDescription
				dataType: string
				lineageTag: 81f62ecc-fa49-4fec-8b09-4c867af5eb16
				summarizeBy: none
				sourceColumn: EnglishDescription

				annotation SummarizationSetBy = Automatic

			column FrenchDescription
				dataType: string
				lineageTag: 55f90145-db20-4437-b164-ae7dd6a1730f
				summarizeBy: none
				sourceColumn: FrenchDescription

				annotation SummarizationSetBy = Automatic

			column ChineseDescription
				dataType: string
				lineageTag: 0c71d3a9-484a-4d1c-9b6e-d8bf0135a2b9
				summarizeBy: none
				sourceColumn: ChineseDescription

				annotation SummarizationSetBy = Automatic

			column ArabicDescription
				dataType: string
				lineageTag: 26db0793-dc18-47c6-8f5c-b2272d27ff21
				summarizeBy: none
				sourceColumn: ArabicDescription

				annotation SummarizationSetBy = Automatic

			column HebrewDescription
				dataType: string
				lineageTag: 8b3c61b0-3cb3-48b3-a289-dd8650f5ec76
				summarizeBy: none
				sourceColumn: HebrewDescription

				annotation SummarizationSetBy = Automatic

			column ThaiDescription
				dataType: string
				lineageTag: d148cc97-ccf6-42c5-985e-14a982f6366f
				summarizeBy: none
				sourceColumn: ThaiDescription

				annotation SummarizationSetBy = Automatic

			column GermanDescription
				dataType: string
				lineageTag: ee9514c1-7164-4aa0-8c37-123de767f7b0
				summarizeBy: none
				sourceColumn: GermanDescription

				annotation SummarizationSetBy = Automatic

			column JapaneseDescription
				dataType: string
				lineageTag: 339c511f-98f5-4aba-9231-6118b585db87
				summarizeBy: none
				sourceColumn: JapaneseDescription

				annotation SummarizationSetBy = Automatic

			column TurkishDescription
				dataType: string
				lineageTag: 384cad47-91c1-48bd-8da7-7a5b276d7a66
				summarizeBy: none
				sourceColumn: TurkishDescription

				annotation SummarizationSetBy = Automatic

			column StartDate
				dataType: dateTime
				formatString: General Date
				lineageTag: fab0d35b-1613-495c-84eb-2ab76bf4f2e3
				summarizeBy: none
				sourceColumn: StartDate

				annotation SummarizationSetBy = Automatic

			column EndDate
				dataType: dateTime
				formatString: General Date
				lineageTag: 470ccfe1-6f32-44e9-8b7a-7c00226b3d55
				summarizeBy: none
				sourceColumn: EndDate

				annotation SummarizationSetBy = Automatic

			column Status
				dataType: string
				lineageTag: 8ec29fc3-e599-42da-80db-8f3007c6b297
				summarizeBy: none
				sourceColumn: Status

				annotation SummarizationSetBy = Automatic

			partition dimproduct = m
				mode: import
				source =
						let
						    Source = Sql.Database("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com", "Lakehouse_Adventure_Works"),
						    dbo_dimproduct = Source{[Schema="dbo",Item="dimproduct"]}[Data]
						in
						    dbo_dimproduct

			annotation PBI_ResultType = Table

		table dimsalesterritory
			lineageTag: 4ad6203f-7644-4390-a0f6-9e6bb0aa8bec

			column SalesTerritoryKey
				dataType: int64
				formatString: 0
				lineageTag: 199a22ef-0f37-4683-8eb0-6fe3aaeba952
				summarizeBy: none
				sourceColumn: SalesTerritoryKey

				annotation SummarizationSetBy = Automatic

			column SalesTerritoryAlternateKey
				dataType: int64
				formatString: 0
				lineageTag: bfe0429c-ce55-4249-b9e9-21c1ef00209f
				summarizeBy: none
				sourceColumn: SalesTerritoryAlternateKey

				annotation SummarizationSetBy = Automatic

			column SalesTerritoryRegion
				dataType: string
				lineageTag: bf14c20e-e3b7-4372-82b6-d237e4edad35
				summarizeBy: none
				sourceColumn: SalesTerritoryRegion

				annotation SummarizationSetBy = Automatic

			column SalesTerritoryCountry
				dataType: string
				lineageTag: 6cf05a98-0079-4a5e-824c-c8d95743d197
				summarizeBy: none
				sourceColumn: SalesTerritoryCountry

				annotation SummarizationSetBy = Automatic

			column SalesTerritoryGroup
				dataType: string
				lineageTag: 70cd7b5f-e9d5-4324-9e07-cde5f4149371
				summarizeBy: none
				sourceColumn: SalesTerritoryGroup

				annotation SummarizationSetBy = Automatic

			partition dimsalesterritory = m
				mode: import
				source =
						let
						    Source = Sql.Database("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com", "Lakehouse_Adventure_Works"),
						    dbo_dimsalesterritory = Source{[Schema="dbo",Item="dimsalesterritory"]}[Data]
						in
						    dbo_dimsalesterritory

			annotation PBI_ResultType = Table

		table factinternetsales_import
			lineageTag: 6861b433-24d6-4d0d-8c0a-2f487144e07d

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: 24cba919-d3de-493f-9f00-1dc9d8e5aa63
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			column OrderDateKey
				dataType: int64
				formatString: 0
				lineageTag: c5c016c9-6091-4be2-a3b0-128805571515
				summarizeBy: none
				sourceColumn: OrderDateKey

				annotation SummarizationSetBy = Automatic

			column DueDateKey
				dataType: int64
				formatString: 0
				lineageTag: ef861958-77f6-4bf6-9478-62f886f5e2a2
				summarizeBy: count
				sourceColumn: DueDateKey

				annotation SummarizationSetBy = Automatic

			column ShipDateKey
				dataType: int64
				formatString: 0
				lineageTag: cca82b1e-da09-4278-8f15-e1d10d275a38
				summarizeBy: count
				sourceColumn: ShipDateKey

				annotation SummarizationSetBy = Automatic

			column CustomerKey
				dataType: int64
				formatString: 0
				lineageTag: ede6c990-1fbc-49d9-a883-abc6dbd3be44
				summarizeBy: none
				sourceColumn: CustomerKey

				annotation SummarizationSetBy = Automatic

			column PromotionKey
				dataType: int64
				formatString: 0
				lineageTag: d699a388-c590-4bd9-82ff-bfa093b10788
				summarizeBy: count
				sourceColumn: PromotionKey

				annotation SummarizationSetBy = Automatic

			column CurrencyKey
				dataType: int64
				formatString: 0
				lineageTag: a52ffacb-e164-4b65-ab7b-da14a94a559f
				summarizeBy: count
				sourceColumn: CurrencyKey

				annotation SummarizationSetBy = Automatic

			column SalesTerritoryKey
				dataType: int64
				formatString: 0
				lineageTag: d4a7b102-6a96-44cf-9747-4b933ba89f8e
				summarizeBy: none
				sourceColumn: SalesTerritoryKey

				annotation SummarizationSetBy = Automatic

			column SalesOrderNumber
				dataType: string
				lineageTag: 9add4348-e123-4aef-acdf-6e8dd885a9bb
				summarizeBy: none
				sourceColumn: SalesOrderNumber

				annotation SummarizationSetBy = Automatic

			column SalesOrderLineNumber
				dataType: int64
				formatString: 0
				lineageTag: 0a2bf5a9-db53-440a-87a9-2f5974124175
				summarizeBy: sum
				sourceColumn: SalesOrderLineNumber

				annotation SummarizationSetBy = Automatic

			column RevisionNumber
				dataType: int64
				formatString: 0
				lineageTag: d935d2ce-a4aa-4913-bb8c-3636ab74ffbc
				summarizeBy: sum
				sourceColumn: RevisionNumber

				annotation SummarizationSetBy = Automatic

			column OrderQuantity
				dataType: int64
				formatString: 0
				lineageTag: 65620d9f-299e-41d6-9c94-33ee8a9a7566
				summarizeBy: sum
				sourceColumn: OrderQuantity

				annotation SummarizationSetBy = Automatic

			column UnitPrice
				dataType: double
				lineageTag: 219a9bb4-4086-44d2-af69-8be5b711dd31
				summarizeBy: sum
				sourceColumn: UnitPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column ExtendedAmount
				dataType: double
				lineageTag: 2af7642c-9320-47e7-acf2-a8e0e67eda13
				summarizeBy: sum
				sourceColumn: ExtendedAmount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column UnitPriceDiscountPct
				dataType: double
				lineageTag: a241bd71-55d0-467b-b82f-7369f773e4a5
				summarizeBy: sum
				sourceColumn: UnitPriceDiscountPct

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column DiscountAmount
				dataType: double
				lineageTag: abf1b7fd-1331-420f-83f0-6839d3a1d9a1
				summarizeBy: sum
				sourceColumn: DiscountAmount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column ProductStandardCost
				dataType: double
				lineageTag: 62a3879f-6575-4500-935a-47b952e9e39f
				summarizeBy: sum
				sourceColumn: ProductStandardCost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column TotalProductCost
				dataType: double
				lineageTag: 85b68cce-0c6c-4493-9d26-b69b067443cb
				summarizeBy: sum
				sourceColumn: TotalProductCost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column SalesAmount
				dataType: double
				lineageTag: 1424be6b-36cd-40e7-93c3-130bd67aa904
				summarizeBy: sum
				sourceColumn: SalesAmount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column TaxAmt
				dataType: double
				lineageTag: de04bd6f-2a6e-4f00-b0a1-041d04b0c318
				summarizeBy: sum
				sourceColumn: TaxAmt

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Freight
				dataType: double
				lineageTag: 36c7b5e1-a462-40fd-a414-c925b471a924
				summarizeBy: sum
				sourceColumn: Freight

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column OrderDate
				dataType: dateTime
				formatString: General Date
				lineageTag: bf7118fc-7780-4d8d-8491-84067b0bb975
				summarizeBy: none
				sourceColumn: OrderDate

				annotation SummarizationSetBy = Automatic

			column DueDate
				dataType: dateTime
				formatString: General Date
				lineageTag: 8ed7e475-9d28-4d40-addc-f98e6e583560
				summarizeBy: none
				sourceColumn: DueDate

				annotation SummarizationSetBy = Automatic

			column ShipDate
				dataType: dateTime
				formatString: General Date
				lineageTag: 1f3eb787-92a6-4459-b4a0-c0af1e9f1f0b
				summarizeBy: none
				sourceColumn: ShipDate

				annotation SummarizationSetBy = Automatic

			partition factinternetsales_import = m
				mode: import
				source =
						let
						    Source = Sql.Database("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com", "Lakehouse_Adventure_Works"),
						    dbo_factinternetsales = Source{[Schema="dbo",Item="factinternetsales"]}[Data]
						in
						    dbo_factinternetsales

			annotation PBI_ResultType = Table

		table dimcustomer
			lineageTag: 02c7a9b7-7fe0-46d3-a27a-f427dd88d0ea

			column CustomerKey
				dataType: int64
				formatString: 0
				lineageTag: dc28d288-06fb-4dd5-b287-3cca9e775fd9
				summarizeBy: none
				sourceColumn: CustomerKey

				annotation SummarizationSetBy = Automatic

			column GeographyKey
				dataType: int64
				formatString: 0
				lineageTag: dd03d35a-99b4-45f0-b21f-ff2785dae4f0
				summarizeBy: none
				sourceColumn: GeographyKey

				annotation SummarizationSetBy = Automatic

			column CustomerAlternateKey
				dataType: string
				lineageTag: 4113abb9-81a3-4031-b5c9-028435354fcc
				summarizeBy: none
				sourceColumn: CustomerAlternateKey

				annotation SummarizationSetBy = Automatic

			column Title
				dataType: string
				lineageTag: 71bf1361-cfad-409b-bbb3-33b6d509725e
				summarizeBy: none
				sourceColumn: Title

				annotation SummarizationSetBy = Automatic

			column FirstName
				dataType: string
				lineageTag: e947588b-0238-45f1-a5ca-b50b6ad0e1a7
				summarizeBy: none
				sourceColumn: FirstName

				annotation SummarizationSetBy = Automatic

			column MiddleName
				dataType: string
				lineageTag: 582389fb-9290-4c74-bca4-413b510fdf4b
				summarizeBy: none
				sourceColumn: MiddleName

				annotation SummarizationSetBy = Automatic

			column LastName
				dataType: string
				lineageTag: 8470c5a8-2f64-4e40-bb65-518fecbfc4ec
				summarizeBy: none
				sourceColumn: LastName

				annotation SummarizationSetBy = Automatic

			column NameStyle
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				lineageTag: 30edb348-ecb4-4a7e-8fb1-fca4a62933dd
				summarizeBy: none
				sourceColumn: NameStyle

				annotation SummarizationSetBy = Automatic

			column BirthDate
				dataType: dateTime
				formatString: Long Date
				lineageTag: 9c9e41a1-9168-43e6-a95c-7d7a75b2d9e0
				summarizeBy: none
				sourceColumn: BirthDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column MaritalStatus
				dataType: string
				lineageTag: e7d2021d-3f83-441d-a5d7-fe0153c9d5ea
				summarizeBy: none
				sourceColumn: MaritalStatus

				annotation SummarizationSetBy = Automatic

			column Suffix
				dataType: string
				lineageTag: b384a5e3-d097-4439-97d7-d80637c65b87
				summarizeBy: none
				sourceColumn: Suffix

				annotation SummarizationSetBy = Automatic

			column Gender
				dataType: string
				lineageTag: 16d9bfbb-5654-497a-8e30-c04fd5f25ec8
				summarizeBy: none
				sourceColumn: Gender

				annotation SummarizationSetBy = Automatic

			column EmailAddress
				dataType: string
				lineageTag: da65405e-ccc6-4a1d-959e-411d1a36e212
				summarizeBy: none
				sourceColumn: EmailAddress

				annotation SummarizationSetBy = Automatic

			column YearlyIncome
				dataType: double
				lineageTag: a310782e-e3ff-4e0e-94de-d28d4de82cc0
				summarizeBy: none
				sourceColumn: YearlyIncome

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column TotalChildren
				dataType: int64
				formatString: 0
				lineageTag: d46ae713-5a81-42c1-8f93-1318ed77a5ae
				summarizeBy: none
				sourceColumn: TotalChildren

				annotation SummarizationSetBy = Automatic

			column NumberChildrenAtHome
				dataType: int64
				formatString: 0
				lineageTag: 8f4759f5-6af1-4c02-80d7-79338ffa64e1
				summarizeBy: none
				sourceColumn: NumberChildrenAtHome

				annotation SummarizationSetBy = Automatic

			column EnglishEducation
				dataType: string
				lineageTag: 72742467-d3a9-42e9-a79f-282ebe8d498b
				summarizeBy: none
				sourceColumn: EnglishEducation

				annotation SummarizationSetBy = Automatic

			column SpanishEducation
				dataType: string
				lineageTag: 52c88d92-db49-4524-8c65-44194853063b
				summarizeBy: none
				sourceColumn: SpanishEducation

				annotation SummarizationSetBy = Automatic

			column FrenchEducation
				dataType: string
				lineageTag: f4c94098-7200-4abf-b2b1-6519a26fbd0a
				summarizeBy: none
				sourceColumn: FrenchEducation

				annotation SummarizationSetBy = Automatic

			column EnglishOccupation
				dataType: string
				lineageTag: dc00dbdd-a9e9-4a71-a959-8aa101ef5ce4
				summarizeBy: none
				sourceColumn: EnglishOccupation

				annotation SummarizationSetBy = Automatic

			column SpanishOccupation
				dataType: string
				lineageTag: a46cf4c9-e3ae-470f-a2b1-9ed15f21cc7d
				summarizeBy: none
				sourceColumn: SpanishOccupation

				annotation SummarizationSetBy = Automatic

			column FrenchOccupation
				dataType: string
				lineageTag: 707192d5-6507-4578-9402-84933cb7b5c1
				summarizeBy: none
				sourceColumn: FrenchOccupation

				annotation SummarizationSetBy = Automatic

			column HouseOwnerFlag
				dataType: string
				lineageTag: d3449ae8-01ec-414c-ab72-a6e5e6868d28
				summarizeBy: none
				sourceColumn: HouseOwnerFlag

				annotation SummarizationSetBy = Automatic

			column NumberCarsOwned
				dataType: int64
				formatString: 0
				lineageTag: b9ce58a5-b9f4-4702-9da6-3a32532b85b5
				summarizeBy: none
				sourceColumn: NumberCarsOwned

				annotation SummarizationSetBy = Automatic

			column AddressLine1
				dataType: string
				lineageTag: df7b20a9-a40c-4834-ad2e-8750dcddb389
				summarizeBy: none
				sourceColumn: AddressLine1

				annotation SummarizationSetBy = Automatic

			column AddressLine2
				dataType: string
				lineageTag: 773aa197-0190-446a-a6b5-66e9434f916d
				summarizeBy: none
				sourceColumn: AddressLine2

				annotation SummarizationSetBy = Automatic

			column Phone
				dataType: string
				lineageTag: 4fb67307-771c-49fe-af92-0ba2e69bd8e7
				summarizeBy: none
				sourceColumn: Phone

				annotation SummarizationSetBy = Automatic

			column DateFirstPurchase
				dataType: dateTime
				formatString: Long Date
				lineageTag: 61deec52-e205-49d6-9762-663e2e85a5de
				summarizeBy: none
				sourceColumn: DateFirstPurchase

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column CommuteDistance
				dataType: string
				lineageTag: e0d38d1f-fda9-4c69-95c9-36ddaf429f76
				summarizeBy: none
				sourceColumn: CommuteDistance

				annotation SummarizationSetBy = Automatic

			partition dimcustomer = m
				mode: import
				source =
						let
						    Source = Sql.Database("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com", "Lakehouse_Adventure_Works"),
						    dbo_dimcustomer = Source{[Schema="dbo",Item="dimcustomer"]}[Data]
						in
						    dbo_dimcustomer

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table prm_category
			lineageTag: f4055d50-4f68-46e4-8226-2fde4d02095c

			column prm_category
				lineageTag: fbeccb21-7e73-44b5-8649-a3131a44818f
				summarizeBy: none
				sourceColumn: [Value1]
				sortByColumn: 'prm_category Order'

				relatedColumnDetails
					groupByColumn: 'prm_category Fields'

				annotation SummarizationSetBy = Automatic

			column 'prm_category Fields'
				isHidden
				lineageTag: cc8ac9ed-442d-4cf4-871d-60349751ca3b
				summarizeBy: none
				sourceColumn: [Value2]
				sortByColumn: 'prm_category Order'

				extendedProperty ParameterMetadata =
						{
						  "version": 3,
						  "kind": 2
						}

				annotation SummarizationSetBy = Automatic

			column 'prm_category Order'
				isHidden
				formatString: 0
				lineageTag: 49fe9496-22d5-4a78-9088-80af9a44eabc
				summarizeBy: sum
				sourceColumn: [Value3]

				annotation SummarizationSetBy = Automatic

			partition prm_category = calculated
				mode: import
				source =
						{
						    ("Gender", NAMEOF('dimcustomer'[Gender]), 0),
						    ("CalendarYear", NAMEOF('dimdate'[CalendarYear]), 1),
						    ("Color", NAMEOF('dimproduct'[Color]), 2),
						    ("EnglishProductName", NAMEOF('dimproduct'[EnglishProductName]), 3),
						    ("SalesTerritoryCountry", NAMEOF('dimsalesterritory'[SalesTerritoryCountry]), 4)
						}

			annotation PBI_Id = dd43d8bd981d400686bf676b4cfb054e

		table Measure
			lineageTag: 312f7673-9bb9-4e6c-b328-9ba9d5df38c0

			measure sales: = SUM(factinternetsales_import[SalesAmount])
				lineageTag: 3d715a5f-b0c8-4a86-9d1b-f88c2590f94d

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'sales SPLY:' = _fn_SamePeriodLastYear([sales:], dimdate[FullDateAlternateKey])
				formatString: #,0.00
				lineageTag: 4e3cfefb-7e12-44ea-b7dc-c690ec3ba67f

			partition Measure = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
						    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
						in
						    #"Removed Columns"

			annotation PBI_ResultType = Table

		relationship AutoDetected_d2b20675-3e31-473e-9f9a-fcb11f050f3a
			fromColumn: factinternetsales_import.ProductKey
			toColumn: dimproduct.ProductKey

		relationship AutoDetected_f1e72363-2a34-4d60-82d5-04b5f82ac268
			fromColumn: factinternetsales_import.SalesTerritoryKey
			toColumn: dimsalesterritory.SalesTerritoryKey

		relationship AutoDetected_28fab9de-380a-4c2d-ba66-60cb7770543d
			fromColumn: factinternetsales_import.CustomerKey
			toColumn: dimcustomer.CustomerKey

		relationship e8f2d1d9-fe27-2894-8920-2354ebe32a54
			fromColumn: factinternetsales_import.OrderDateKey
			toColumn: dimdate.DateKey

		cultureInfo en-US

			linguisticMetadata = {"Version":"2.0.0","Language":"en-US","Entities":{"dimdate.calendaryear":{"Definition":{"Binding":{"ConceptualEntity":"dimdate","ConceptualProperty":"CalendarYear"}},"State":"Generated","Terms":[{"CalendarYear":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]}}}
				contentType: json

		function _fn_SamePeriodLastYear =
				(_measure: int64 expr, _datecolumn: anyref) => CALCULATE(
							_measure,
							SAMEPERIODLASTYEAR(_datecolumn)
						)
			lineageTag: d0b4b437-583a-4445-9b53-5e0de08374ee

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_ProTooling = ["DevMode","TMDLView_Desktop"]

		annotation PBI_QueryOrder = ["dimdate","dimproduct","dimsalesterritory","factinternetsales_import","dimcustomer","Measure"]

